### ISSUE TITLE
Cannot select build configuration if more than one is available

### ISSUE THREAD

**Issue by spacecoder007** [ndrone/teamcity-trigger-plugin#1]
On selection, it reselects the first in the list.

**Comment by ndrone** [comment]
When the selection window is clicked it refreshes the list of build configurations from TeamCity. And yes the first in the list is selected. But after that I have no problems selecting a different build configuration. Is the issue that truly what the title says or that it selects the first build configuration from the list?

**Comment by spacecoder007** [comment]
I tried selecting one further down the list, but on selection, the first build was shown again.

**Comment by ndrone** [comment]
OK I'll take a look into it... which browser, and version are you using by chance?

**Comment by ndrone** [comment]
I was able to reproduce it... If you click and hold then you will get a list, and then can select from as a work around for now. I'll get this fixed right away.

**Comment by spacecoder007** [comment]
Great, thanks :)

**Comment by ndrone** [comment]
fixed added a refresh button next to the select box
